meta_product_name: "Mix And Match"
meta_title: "MixAndMatch - Listes de tâches aléatoires"
meta_description: "Avec MixAndMatch, répartissez aléatoirement les tâches entre les membres de votre équipe ou de votre famille."
meta_image: "cover.png" # should exist in `app/assets/images/`



